baseurl = "https://turtletooth.com/"
title = "TurtleTooth"
theme = "turtletooth"
languageCode = "en-us"

# Define the number of posts per page
paginate = 3

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"


[params]
    viewMorePostLink     = "/blog/"
    author = "Jeremy Bullock"
    email = "jcbullock@gmail.com"
    about_us = "<p>TurtleTooth is the website of Jeremy Bullock</p>"
    copyright = "Copyright &copy; 2015 - 2018, TurtleTooth Media.  All Rights Reserved."
    date_format = "2006-01-02"
    logo = "img/logo.png"
    address = """<p><strong>TurtleTooth</strong>

        <br>Colorado Springs, CO
        <br>
        <strong>U.S.A.</strong>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[[params.menu]]
    name = "Home"
    url  = "/"
    weight = 1

[[params.menu]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[params.menu]]
    name = "Contact"
    url  = "/contact/"
    weight = 3

[[params.dropdown]]
    name = "OpenToonz"
    url = "/opentoonz"
    weight = 1

[[params.dropdown]]
    name = "Godot"
    url = "/godot"
    weight = 2

[[params.links]]
    name = "Google Classroom"
    url = "http://classroom.google.com"
    weight = 0

[[params.links]]
    name = "Eagleview Homepage"
    url = "https://eagleview.asd20.org/Pages/default.aspx"
    weight = 1

[[params.broadcastlinks]]
    name = "Talon Homepage"
    url = "http://eagleviewmedia.org"
    weight = 1

[[params.broadcastlinks]]
    name = "Broadcast Calendar"
    url = "../calendar/broadcast"
    weight = 2

[[params.photographylinks]]
    name = "Pic Monkey"
    url = "http://picmonkey.com"
    weight = 1

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true
